---
- name: Include RedHat setup tasks
  ansible.builtin.include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Debian setup tasks
  ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Filebeat.
  ansible.builtin.package:
    name: "{{ filebeat_package }}"
    state: "{{ filebeat_package_state }}"

- name: Include config tasks
  ansible.builtin.include_tasks:
    file: config.yml
  when: filebeat_create_config | bool

- name: Ensure Filebeat is started and enabled at boot.
  ansible.builtin.service:
    name: filebeat
    state: started
    enabled: true
